SlikMusik/Models/CreateUser.cs
using System.ComponentModel.DataAnnotations;

namespace SlikMusik.Models
{
    public class CreateUser
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

SlikMusik/Models/LoginUser.cs
using System.ComponentModel.DataAnnotations;

namespace SlikMusik.Models
{
    public class LoginUser
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

SlikMusik/Controllers/MerchandizeController.cs
using System.Web.Mvc;
using SlikMusik.Authorization;
using SlikMusik.Core;

namespace SlikMusik.Controllers
{
    public class MerchandizeController : Controller
    {
        private readonly StoreUserRequestListener userRequestListener =
            new StoreClerk(new EfInventory());

        [StoreOwnerAuthorization]
        public ActionResult Create(int storeId)
        {
            return View(new Merchandize() {StoreId = storeId});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [StoreOwnerAuthorization]
        public ActionResult Create(Merchandize merch)
        {
            if (ModelState.IsValid)
            {
                userRequestListener.AddToInventory(merch);
                return RedirectToAction("Visit", "Store", new {id = merch.StoreId});
            }
            return View();
        }

        public ActionResult Show(int storeId, int id)
        {
            return View(userRequestListener.GetMerchandize(id));
        }
    }
}

SlikMusik/Controllers/ShoppingCartController.cs
using System.Web.Mvc;
using SlikMusik.Core;

namespace SlikMusik.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly StoreUserRequestListener userRequestListener =
            new StoreClerk(new EfInventory(new EfDbContext()));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(int id)
        {
            userRequestListener.AddToShoppingCart(ShoppingCart, id);
            return RedirectToAction("Show");
        }

        public ActionResult Show()
        {
            return View(ShoppingCart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Remove(int id)
        {
            ShoppingCart.Remove(id);
            return RedirectToAction("Show");
        }

        private ShoppingCart ShoppingCart
        {
            get
            {
                var cart = SessionShoppingCart.From((ShoppingCart) Session["ShoppingCart"]);
                Session["ShoppingCart"] = cart;
                return cart;
            }
        }
    }
}

SlikMusik/Controllers/StoreController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SlikMusik.Authorization;
using SlikMusik.Core;

namespace SlikMusik.Controllers
{
    public class StoreController : Controller
    {
        private readonly StoreRegistry storeRegistry = new EfStoreRegistry();

        public ActionResult Visit(int id)
        {
            var store = storeRegistry.FindStore(id);
            ViewBag.IsStoreOwner = store.HasOwner(HttpContext.User.Identity.GetUserId());

            return View(store);
        }

        [Authorize]
        public ActionResult OpenUp()
        {
            return View(new Store());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult OpenUp(Store store)
        {
            if (ModelState.IsValid)
            {
                store.UserId = HttpContext.User.Identity.GetUserId();
                storeRegistry.OpenUp(store);

                return RedirectToAction("Visit", new { id = store.Id});
            }

            return View();
        }

        public ActionResult List()
        {
            var stores = storeRegistry.ListAllStores();
            return View(stores);
        }

        [StoreOwnerAuthorization]
        public ActionResult Configure(int id)
        {
            var store = storeRegistry.FindStore(id);
            return View(store);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [StoreOwnerAuthorization]
        public ActionResult Configure(Store store)
        {
            if (ModelState.IsValid)
            {
                storeRegistry.Change(store);

                return RedirectToAction("Visit", new { id = store.Id });
            }

            return View();
        }
    }
}

SlikMusik/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SlikMusik.Identity;
using SlikMusik.Models;

namespace SlikMusik.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateUser model)
        {
            if (ModelState.IsValid)
            {
                var user = new User {UserName = model.Name, Email = model.Email};
                var result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await SignIn(user);
                    return Redirect("/");
                }

                AddErrorsFromResult(result);
            }
            return View(model);
        }

        public ActionResult Login(string returnUrl = "/")
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginUser userDetails, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindAsync(userDetails.Name, userDetails.Password);

                if (user == null)
                {
                    ModelState.AddModelError("", "Invalid email or password.");
                }
                else
                {
                    await SignIn(user);
                    return Redirect(returnUrl);
                }
            }

            return View(userDetails);
        }

        private async Task SignIn(User user)
        {
            var ident = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
            AuthenticationManager.SignOut();
            AuthenticationManager.SignIn(new AuthenticationProperties {IsPersistent = false}, ident);
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            return Redirect("/");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private UserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<UserManager>(); }
        }
    }
}

SlikMusik/Views/Home/Index.cshtml
@using SlikMusik.Domain.Entities
@model IEnumerable<Store>

@{
    ViewBag.Title = "Go on, create your own music store";
}

<h2>Welcome stranger!</h2>
<p>Why don't you just join the others and open up your own store on this nice music market?</p>

@Html.ActionLink("Open up store now!", "OpenUp", "Store")
<small>It's free!</small>

SlikMusik/Views/Merchandize/Create.cshtml
@model SlikMusik.Core.Merchandize
           
@{
    ViewBag.Title = "Add your great merchandize";
}

<h2>Add your great merchandize</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(store => store.StoreId)
    
    <label>
        Name
        @Html.TextBoxFor(merch => merch.Name)
    </label>
    <label>
        Price
        @Html.TextBoxFor(merch => merch.Price)
    </label>
    <button type="submit">Add it!</button>
}

SlikMusik/Views/Merchandize/Show.cshtml
@model SlikMusik.Core.Merchandize

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name</h2>
<div>Price: @Model.Price.ToString("C")</div>
@using (Html.BeginForm("Add", "ShoppingCart"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(merch => merch.Id)
    <button type="submit">Add to shopping cart</button>
}

SlikMusik/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - SlikMusik</title>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.2.2/css/normalize.min.css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.2.2/css/foundation.min.css">
    </head>
    <body>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1>@Html.ActionLink("SlikMusik", "List", "Store")</h1> 
                </li>
                <li class="toggle-topbar menu-icon">
                    <a href="#">Menu</a>
                </li> 
            </ul>
            <section class="top-bar-section">
                <!-- Right Nav Section -->
                <ul class="right">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "User")</li>
                        <li>@Html.ActionLink("Get aboard and register", "Create", "User")</li>
                    }
                    <li>@Html.ActionLink("Your shopping cart", "Show", "ShoppingCart")</li>
                </ul>
            </section> 
        </nav>
        <div class="row">
            @RenderBody()
        </div>
    </body>
</html>

SlikMusik/Views/ShoppingCart/Show.cshtml
@model SlikMusik.Core.ShoppingCart

@{
    ViewBag.Title = "Your shopping cart";
}

<h2>Your shopping cart</h2>

<ul>
    @foreach (var item in Model.Content)
    {
        <li>
            @item.Name - @item.Price.ToString("C")
            @using (Html.BeginForm("Remove", "ShoppingCart")) {
                @Html.AntiForgeryToken()
                
                @Html.Hidden("id", item.Id)
                <button type="submit">Remove</button>
            }
        </li>
    }
</ul>

SlikMusik/Views/Store/Configure.cshtml
@model SlikMusik.Core.Store

@{
    ViewBag.Title = "Configure your store";
}

<h2>Configure your store</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <label>
        Name
        @Html.TextBoxFor(store => store.Name)
    </label>
    <button type="submit">Save Changes</button>
}

@Html.ActionLink("Add merchandize to this store", "Create", "Merchandize", new {storeId = Model.Id}, new {@class = "button"})

@Html.ActionLink("Back to Store", "Visit", new {id = Model.Id})

SlikMusik/Views/Store/List.cshtml
@model IEnumerable<SlikMusik.Core.Store>

@{
    ViewBag.Title = "Go on, create your own music store";
}

<h2>Welcome stranger!</h2>
<p>Why don't you just join the others and open up your own store on this nice music market?</p>

@Html.ActionLink("Open up a store now!", "OpenUp", "Store", new {@class = "button"})
<small>It's free!</small>

<h3>These artists have already opened up their store here</h3>
<ul class="small-block-grid-3">
    @foreach (var store in Model)
    {
        <li>@Html.ActionLink(store.Name, "Visit", new { id = store.Id })</li>
    }
</ul>

SlikMusik/Views/Store/OpenUp.cshtml
@model SlikMusik.Core.Store

@{
    ViewBag.Title = "Open up your own store";
}

<h2>Open up your own store</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <label>
        Name
        @Html.TextBoxFor(store => store.Name)
    </label>

    <button type="submit">Open It Up!</button>
}

SlikMusik/Views/Store/Visit.cshtml
@model SlikMusik.Core.Store

@{
    ViewBag.Title = "title";
}

<h2>@Model.Name</h2>

<h3>@Model.Name Stock (@Model.InventorySize)</h3>

<ul>
    @foreach (var merchandize in Model.Inventory)
    {
        <li>@Html.ActionLink(merchandize.Name, "Show", "Merchandize", new {storeId = Model.Id, id = merchandize.Id}, null)</li>
    }
</ul>

@if (ViewBag.IsStoreOwner)
{
    @Html.ActionLink("Configure", "Configure", new { id = Model.Id }, new { @class = "button" })
}

SlikMusik/Views/User/Create.cshtml
@model SlikMusik.Models.CreateUser

@{
    ViewBag.Title = "Get aboard the MS SlikMusik";
}

<h2>@ViewBag.Title</h2>

@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <label>
        Name
        @Html.TextBoxFor(x => x.Name)
    </label>
    <label>
        Email
        @Html.TextBoxFor(x => x.Email)
    </label>
    <label>Password
        @Html.PasswordFor(x => x.Password)
    </label>
    <button type="submit">Get me aboard!</button>
}

SlikMusik/Views/User/Login.cshtml
@model SlikMusik.Models.LoginUser

@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title</h2>

@Html.ValidationSummary()

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />
    <label>
        Name
        @Html.TextBoxFor(x => x.Name)
    </label>
    <label>
        Password
        @Html.PasswordFor(x => x.Password)
    </label>
    <button type="submit">Log In</button>
}